apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-replicacontroller
  labels:
    app: myapp
    type: frontend
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp-nginx-container
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 2
