apiVersion: v1
kind: ResourceQuota
metadata:
  name: vimlesh-ns-quota
  namespace: vimlesh
spec:
    hard:
        pods: "10"
        requests.cpu: "2"
        requests.memory: 4Gi
        limits.cpu: "3"
        limits.memory: 5Gi
