apiVersion: v1
kind: Pod
metadata:
    name: nginx-pod
    labels:
        app: front-end
        sub-tier: welcome
spec:
    containers:
        - name: nginx-container
          image: nginx
          envFrom:
              - configMapRef:
                    name: app-config
          env:
              - name: APP_COLOR
                value: Blue
