apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp
  labels:
    app: myapp
    type: frontend
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
    spec:
      containers:
        - name: probe
          image: vimlesh/probe
          ports:
    	    - containerPort: 8000
  replicas: 3
  selector:
    matchLabels:
      app: myapp

