apiVersion: v1
kind: Pod
metadata:
    name: ubuntu-security-context
spec:
    containers:
        - image: ubuntu
          name: ubuntu-cont
          command: 
              - "sleep"
              -  "5000"
          securityContext:
             runAsUser: 1000
             capabilities:
                 add: ["MAC_ADMIN"]
